### ISSUE TITLE
PixelStorei unimplemented

### ISSUE THREAD

**Issue by BriSeven** [puffnfresh/node-webgl#2]
Hello, just given this a little try, and the example uses the above named method, but the node module fails to implement it.

I've gone ahead and implemented it myself. (I need to fix my ssh issues before I can push my change back to my git repo)

Which compiles, and runs, but the bouncing node logo is still missing.

**Comment by puffnfresh** [comment]
Thanks! The bouncing node logo got broken by a recent change. I'll try to work on fixing it tonight.

**Comment by BriSeven** [comment]
any luck? What is the most recent commit before the breaking change?

**Comment by puffnfresh** [comment]
Maybe it isn't a change that I made. I can't get DevIL to load any PNG files on my systems.

I'm in the process of changing to FreeImage - much better API and it's already somewhat working.

**Comment by puffnfresh** [comment]
Committed the move to FreeImage in 70877b4e299310fe5c54. Let me know if it works on your system.

Eager for your patch.

**Comment by BriSeven** [comment]
Yes it works now- Which rather renders my patch moot. But it's an interesting project, and I've got it in my todo list to work on.
